import type { Word } from './types'

export const WORDS: Word[] = [
  { id: 'apple',  text: '사과',   theme: 'food',     image: { type: 'fluent', name: 'apple' } },
  { id: 'banana', text: '바나나', theme: 'food',     image: { type: 'fluent', name: 'banana' } },
  { id: 'grape',  text: '포도',   theme: 'food',     image: { type: 'fluent', name: 'grape' } },
  { id: 'dog',    text: '강아지', theme: 'animals',  image: { type: 'fluent', name: 'dog' } },
  { id: 'cat',    text: '고양이', theme: 'animals',  image: { type: 'fluent', name: 'cat' } },
  { id: 'rabbit', text: '토끼',   theme: 'animals',  image: { type: 'fluent', name: 'rabbit' } },
  { id: 'car',    text: '자동차', theme: 'vehicles', image: { type: 'fluent', name: 'car' } },
  { id: 'bus',    text: '버스',   theme: 'vehicles', image: { type: 'fluent', name: 'bus' } },
  { id: 'star',   text: '별',     theme: 'nature',   image: { type: 'fluent', name: 'star' } },
  { id: 'moon',   text: '달',     theme: 'nature',   image: { type: 'fluent', name: 'moon' } },
  { id: 'flower', text: '꽃',     theme: 'nature',   image: { type: 'fluent', name: 'flower' } },
  { id: 'ball',   text: '공',     theme: 'home',     image: { type: 'fluent', name: 'ball' } },
  // 탈것
  { id: 'train',    text: '기차',   theme: 'vehicles',   image: { type: 'fluent', name: 'train' } },
  { id: 'airplane', text: '비행기', theme: 'vehicles',   image: { type: 'fluent', name: 'airplane' } },
  // 색깔
  { id: 'red',    text: '빨강',   theme: 'colorshape', image: { type: 'fluent', name: 'red' } },
  { id: 'blue',   text: '파랑',   theme: 'colorshape', image: { type: 'fluent', name: 'blue' } },
  { id: 'yellow', text: '노랑',   theme: 'colorshape', image: { type: 'fluent', name: 'yellow' } },
  // 가족
  { id: 'mom',    text: '엄마',   theme: 'family',     image: { type: 'fluent', name: 'mom' } },
  { id: 'dad',    text: '아빠',   theme: 'family',     image: { type: 'fluent', name: 'dad' } },
  { id: 'baby',   text: '아기',   theme: 'family',     image: { type: 'fluent', name: 'baby' } },
  // 동물 더
  { id: 'bear',     text: '곰',     theme: 'animals', image: { type: 'fluent', name: 'bear' } },
  { id: 'lion',     text: '사자',   theme: 'animals', image: { type: 'fluent', name: 'lion' } },
  { id: 'tiger',    text: '호랑이', theme: 'animals', image: { type: 'fluent', name: 'tiger' } },
  { id: 'elephant', text: '코끼리', theme: 'animals', image: { type: 'fluent', name: 'elephant' } },
  { id: 'monkey',   text: '원숭이', theme: 'animals', image: { type: 'fluent', name: 'monkey' } },
  { id: 'penguin',  text: '펭귄',   theme: 'animals', image: { type: 'fluent', name: 'penguin' } },
  { id: 'bird',     text: '새',     theme: 'animals', image: { type: 'fluent', name: 'bird' } },
  { id: 'fish',     text: '물고기', theme: 'animals', image: { type: 'fluent', name: 'fish' } },
  { id: 'pig',      text: '돼지',   theme: 'animals', image: { type: 'fluent', name: 'pig' } },
  { id: 'frog',     text: '개구리', theme: 'animals', image: { type: 'fluent', name: 'frog' } },
  // 과일·음식
  { id: 'strawberry', text: '딸기',     theme: 'food', image: { type: 'fluent', name: 'strawberry' } },
  { id: 'watermelon', text: '수박',     theme: 'food', image: { type: 'fluent', name: 'watermelon' } },
  { id: 'tangerine',  text: '귤',       theme: 'food', image: { type: 'fluent', name: 'tangerine' } },
  { id: 'lemon',      text: '레몬',     theme: 'food', image: { type: 'fluent', name: 'lemon' } },
  { id: 'peach',      text: '복숭아',   theme: 'food', image: { type: 'fluent', name: 'peach' } },
  { id: 'rice',       text: '밥',       theme: 'food', image: { type: 'fluent', name: 'rice' } },
  { id: 'bread',      text: '빵',       theme: 'food', image: { type: 'fluent', name: 'bread' } },
  { id: 'milk',       text: '우유',     theme: 'food', image: { type: 'fluent', name: 'milk' } },
  { id: 'candy',      text: '사탕',     theme: 'food', image: { type: 'fluent', name: 'candy' } },
  { id: 'cake',       text: '케이크',   theme: 'food', image: { type: 'fluent', name: 'cake' } },
  { id: 'egg',        text: '계란',     theme: 'food', image: { type: 'fluent', name: 'egg' } },
  { id: 'icecream',   text: '아이스크림', theme: 'food', image: { type: 'fluent', name: 'icecream' } },
  { id: 'cookie',     text: '과자',     theme: 'food', image: { type: 'fluent', name: 'cookie' } },
  // 몸
  { id: 'hand',  text: '손', theme: 'body', image: { type: 'fluent', name: 'hand' } },
  { id: 'foot',  text: '발', theme: 'body', image: { type: 'fluent', name: 'foot' } },
  { id: 'eye',   text: '눈', theme: 'body', image: { type: 'fluent', name: 'eye' } },
  { id: 'nose',  text: '코', theme: 'body', image: { type: 'fluent', name: 'nose' } },
  { id: 'ear',   text: '귀', theme: 'body', image: { type: 'fluent', name: 'ear' } },
  { id: 'mouth', text: '입', theme: 'body', image: { type: 'fluent', name: 'mouth' } },
  // 옷·집·사물
  { id: 'hat',    text: '모자', theme: 'home', image: { type: 'fluent', name: 'hat' } },
  { id: 'shoes',  text: '신발', theme: 'home', image: { type: 'fluent', name: 'shoes' } },
  { id: 'socks',  text: '양말', theme: 'home', image: { type: 'fluent', name: 'socks' } },
  { id: 'gloves', text: '장갑', theme: 'home', image: { type: 'fluent', name: 'gloves' } },
  { id: 'house',  text: '집',   theme: 'home', image: { type: 'fluent', name: 'house' } },
  { id: 'chair',  text: '의자', theme: 'home', image: { type: 'fluent', name: 'chair' } },
  { id: 'bed',    text: '침대', theme: 'home', image: { type: 'fluent', name: 'bed' } },
  { id: 'clock',  text: '시계', theme: 'home', image: { type: 'fluent', name: 'clock' } },
  { id: 'book',   text: '책',   theme: 'home', image: { type: 'fluent', name: 'book' } },
  // 자연 더
  { id: 'sun',      text: '해',     theme: 'nature', image: { type: 'fluent', name: 'sun' } },
  { id: 'cloud',    text: '구름',   theme: 'nature', image: { type: 'fluent', name: 'cloud' } },
  { id: 'rain',     text: '비',     theme: 'nature', image: { type: 'fluent', name: 'rain' } },
  { id: 'tree',     text: '나무',   theme: 'nature', image: { type: 'fluent', name: 'tree' } },
  { id: 'mountain', text: '산',     theme: 'nature', image: { type: 'fluent', name: 'mountain' } },
  { id: 'rainbow',  text: '무지개', theme: 'nature', image: { type: 'fluent', name: 'rainbow' } },
  // 탈것 더
  { id: 'boat',   text: '배',     theme: 'vehicles', image: { type: 'fluent', name: 'boat' } },
  { id: 'bike',   text: '자전거', theme: 'vehicles', image: { type: 'fluent', name: 'bike' } },
  { id: 'rocket', text: '로켓',   theme: 'vehicles', image: { type: 'fluent', name: 'rocket' } },
  { id: 'truck',  text: '트럭',   theme: 'vehicles', image: { type: 'fluent', name: 'truck' } },
  // 색깔 더
  { id: 'green',  text: '초록', theme: 'colorshape', image: { type: 'fluent', name: 'green' } },
  { id: 'purple', text: '보라', theme: 'colorshape', image: { type: 'fluent', name: 'purple' } },
  { id: 'white',  text: '하양', theme: 'colorshape', image: { type: 'fluent', name: 'white' } },
  { id: 'black',  text: '검정', theme: 'colorshape', image: { type: 'fluent', name: 'black' } },
  { id: 'brown',  text: '갈색', theme: 'colorshape', image: { type: 'fluent', name: 'brown' } },
]
