// 자동 생성됨 — scripts/gen-tts.mjs. 직접 수정 금지. (텍스트 → mp3 경로)
export const GENERATED_RECORDINGS: Record<string, string> = {
  "\"같이 먹으면 두 배로 맛있어!\" 사과랑 바나나랑 포도를 사이좋게 나눠 먹었어요. 냠냠!": "/audio/tts/8n441g.mp3",
  "\"깡총깡총!\" 토끼가 폴짝폴짝 뛰어와 반갑게 인사했어요.": "/audio/tts/12tkk3j.mp3",
  "\"다음에 또 타러 오자!\" 콩콩이가 활짝 웃으며 손을 흔들었답니다.": "/audio/tts/9g2o3v.mp3",
  "\"멍멍!\" 강아지가 꼬리를 살랑살랑 흔들며 달려왔어요.": "/audio/tts/50tqe5.mp3",
  "\"멍멍!\" 꼬리를 흔들흔들, 강아지가 신나게 달려왔어요.": "/audio/tts/jmy36z.mp3",
  "\"부릉부릉~\" 노란 버스가 친구들을 가득 태우고 왔어요.": "/audio/tts/vpckak.mp3",
  "\"빵빵!\" 빨간 자동차가 쌩하고 바람처럼 지나갔어요.": "/audio/tts/19ew3ew.mp3",
  "\"사랑해요, 잘 자요.\" 가족은 포근한 이불 속에서 스르르 잠들었답니다.": "/audio/tts/fxhw1h.mp3",
  "\"안녕! 또 타러 오자.\" 곰돌이가 손을 흔들었어요.": "/audio/tts/lm0dnj.mp3",
  "\"알록달록 색깔은 정말 신기해!\" 콩콩이가 깔깔 웃었어요.": "/audio/tts/1efwrdd.mp3",
  "\"알록달록 정말 예뻤어!\" 곰돌이가 방긋 웃었어요.": "/audio/tts/17um9qe.mp3",
  "\"야옹~\" 고양이가 살금살금 다가와 인사했어요.": "/audio/tts/109pa4f.mp3",
  "\"야옹~\" 발끝을 살금살금, 고양이가 살며시 다가왔어요.": "/audio/tts/111ndbk.mp3",
  "\"영차!\" 아빠가 콩콩이를 번쩍 안아 하늘 높이 들어 올렸어요.": "/audio/tts/7a2vgi.mp3",
  "\"오늘 정말 재밌었어. 안녕, 또 만나!\" 친구들이 손을 흔들었어요.": "/audio/tts/12uoxqs.mp3",
  "\"오늘 정말 즐거웠어. 내일 또 놀자!\" 친구들은 손을 흔들었어요.": "/audio/tts/2iajcj.mp3",
  "\"우리 아가!\" 엄마가 다정하게 안아 줬어요.": "/audio/tts/d222ap.mp3",
  "\"우리 아가, 이리 오렴.\" 엄마가 두 팔 벌려 콩콩이를 꼭 안아 줬어요.": "/audio/tts/1epqvh4.mp3",
  "\"우아, 빨간 사과가 주렁주렁!\" 곰돌이가 사과를 콕 땄어요.": "/audio/tts/1ipq997.mp3",
  "\"우아, 빨갛게 익은 사과가 주렁주렁!\" 콩콩이가 까치발을 하고 사과를 콕 땄어요.": "/audio/tts/188yn9.mp3",
  "\"이건 사과처럼 빨강 풍선!\" 동그란 빨강이 둥실 떠올랐어요.": "/audio/tts/10aqy7p.mp3",
  "\"이건 하늘처럼 파랑 풍선!\" 시원한 파랑이 살랑살랑 흔들렸어요.": "/audio/tts/5frdah.mp3",
  "\"이건 햇님처럼 노랑 풍선!\" 반짝이는 노랑이 방긋 웃었어요.": "/audio/tts/91zw5m.mp3",
  "\"이리 오렴!\" 아빠가 번쩍 안아 올렸어요.": "/audio/tts/187nash.mp3",
  "\"잘 자, 별님 달님!\" 곰돌이는 새근새근 꿈나라로 갔어요.": "/audio/tts/v5ov2k.mp3",
  "\"잘 자, 별님 달님.\" 콩콩이는 새근새근 꿈나라로 떠났답니다.": "/audio/tts/n0hgv4.mp3",
  "\"잘 자요, 사랑해.\" 온 가족이 포근히 잠들었어요.": "/audio/tts/oax5nz.mp3",
  "\"칙칙폭폭!\" 기차가 산을 넘고 들을 지나 신나게 달렸어요.": "/audio/tts/bbmg6w.mp3",
  "갈": "/audio/tts/4qzx.mp3",
  "갈 글자를 찾아요": "/audio/tts/vmerrj.mp3",
  "갈색": "/audio/tts/4dt06.mp3",
  "갈색 머리": "/audio/tts/16yn0be.mp3",
  "강": "/audio/tts/4r0a.mp3",
  "강 글자를 찾아요": "/audio/tts/pluios.mp3",
  "강아지": "/audio/tts/40pt4u.mp3",
  "강아지랑 고양이랑 토끼랑! 다 함께 공을 데굴데굴 굴리며 놀았어요.": "/audio/tts/1gqqhxy.mp3",
  "같은 글자를 모두 찾아요": "/audio/tts/oz296g.mp3",
  "같은 짝을 맞춰보세요": "/audio/tts/10ck8st.mp3",
  "개": "/audio/tts/4r0h.mp3",
  "개 글자를 찾아요": "/audio/tts/12rc8pv.mp3",
  "개구리": "/audio/tts/40lkex.mp3",
  "검": "/audio/tts/4r39.mp3",
  "검 글자를 찾아요": "/audio/tts/3evjif.mp3",
  "검정": "/audio/tts/4dxi2.mp3",
  "검정 머리": "/audio/tts/1afc1we.mp3",
  "계": "/audio/tts/4r55.mp3",
  "계 글자를 찾아요": "/audio/tts/1yapdjf.mp3",
  "계란": "/audio/tts/4dvyh.mp3",
  "고": "/audio/tts/4r5x.mp3",
  "고 글자를 찾아요": "/audio/tts/1fvk7on.mp3",
  "고깔 모자": "/audio/tts/18e233l.mp3",
  "고양이": "/audio/tts/40ul7u.mp3",
  "고양이 귀": "/audio/tts/1cthglm.mp3",
  "곰": "/audio/tts/4r6d.mp3",
  "곰 글자를 찾아요": "/audio/tts/rey2f.mp3",
  "곰 인형": "/audio/tts/1ouj4f6.mp3",
  "곰돌이가 길가에서 무엇이 올까 기다려요.": "/audio/tts/1paq3ei.mp3",
  "곰돌이가 숲속 길을 따라 살랑살랑 산책을 나갔어요.": "/audio/tts/1frvhmp.mp3",
  "곰돌이가 알록달록 색깔 풍선을 들고 왔어요.": "/audio/tts/1lr38ar.mp3",
  "곰돌이는 별과 달과 꽃을 보며 방긋 웃었어요.": "/audio/tts/1t3puy9.mp3",
  "곰돌이랑 강아지랑 고양이랑 토끼! 다 같이 공을 차며 신나게 놀았어요.": "/audio/tts/1xf7bp3.mp3",
  "공": "/audio/tts/4r6i.mp3",
  "공주 망토": "/audio/tts/1cuw02b.mp3",
  "공주님을 예쁘게 꾸며요": "/audio/tts/ege63e.mp3",
  "과": "/audio/tts/4r6p.mp3",
  "과 글자를 찾아요": "/audio/tts/xgf1tv.mp3",
  "과자": "/audio/tts/4e0k1.mp3",
  "구": "/audio/tts/4r9t.mp3",
  "구 글자를 찾아요": "/audio/tts/usygdv.mp3",
  "구름": "/audio/tts/4e0mt.mp3",
  "귀": "/audio/tts/4rc5.mp3",
  "귀 글자를 찾아요": "/audio/tts/1akn0sn.mp3",
  "귤": "/audio/tts/4rd5.mp3",
  "귤 글자를 찾아요": "/audio/tts/2lf84r.mp3",
  "그림을 보고 맞는 글자를 골라요": "/audio/tts/pfm693.mp3",
  "글자 카드로 단어를 만들어요": "/audio/tts/sao39t.mp3",
  "금발 머리": "/audio/tts/1gaj8i5.mp3",
  "기": "/audio/tts/4rf9.mp3",
  "기 글자를 찾아요": "/audio/tts/17x6fcn.mp3",
  "기본 공주님": "/audio/tts/1f26bva.mp3",
  "기차": "/audio/tts/4e9b1.mp3",
  "깜깜한 하늘에 반짝반짝 별이 하나둘 눈을 떴어요.": "/audio/tts/1wsy7kp.mp3",
  "꽃": "/audio/tts/4rmw.mp3",
  "꽃 글자를 찾아요": "/audio/tts/1h9kkzu.mp3",
  "꽃 정원": "/audio/tts/1p79g99.mp3",
  "꽃 화관": "/audio/tts/1p7bw0s.mp3",
  "꽃다발": "/audio/tts/415enc.mp3",
  "꽃밭": "/audio/tts/4ed5h.mp3",
  "나": "/audio/tts/4rwd.mp3",
  "나 글자를 찾아요": "/audio/tts/1sup6e7.mp3",
  "나무": "/audio/tts/4eln5.mp3",
  "나무 위 원숭이가 \"끼끼!\" 웃으며 길쭉한 바나나를 쑥 내밀었어요.": "/audio/tts/1m1jf5y.mp3",
  "나무 위 원숭이가 방긋 웃으며 노란 바나나를 건넸어요.": "/audio/tts/wiwear.mp3",
  "나비": "/audio/tts/4em8x.mp3",
  "나비 넥타이": "/audio/tts/u3kqqi.mp3",
  "남색 드레스": "/audio/tts/1h4a82m.mp3",
  "노": "/audio/tts/4s2l.mp3",
  "노 글자를 찾아요": "/audio/tts/1njrzi7.mp3",
  "노란 버스가 친구들을 태우고 왔어요.": "/audio/tts/14z4nyj.mp3",
  "노랑": "/audio/tts/4eqmm.mp3",
  "노을": "/audio/tts/4etq9.mp3",
  "눈": "/audio/tts/4s6l.mp3",
  "눈 글자를 찾아요": "/audio/tts/pp4wsv.mp3",
  "눈꽃 왕관": "/audio/tts/1yf8fqd.mp3",
  "눈나라": "/audio/tts/41liip.mp3",
  "다람쥐도 통통한 보라색 포도를 한 송이 데굴데굴 굴려 왔어요.": "/audio/tts/6pmu3z.mp3",
  "다람쥐도 폴짝폴짝 보라색 포도를 한 송이 가져왔어요.": "/audio/tts/1hg2co3.mp3",
  "다시 골라볼까?": "/audio/tts/qus18w.mp3",
  "다시 들어볼까?": "/audio/tts/1x3uz5w.mp3",
  "다시 찾아볼까?": "/audio/tts/1883t66.mp3",
  "다시 해볼까?": "/audio/tts/15g0edc.mp3",
  "단발 머리": "/audio/tts/5qlcj1.mp3",
  "달": "/audio/tts/4scx.mp3",
  "달 글자를 찾아요": "/audio/tts/7m6eib.mp3",
  "달 왕관": "/audio/tts/1prapza.mp3",
  "달빛 아래 예쁜 꽃이 살며시 피었어요.": "/audio/tts/12a4lz1.mp3",
  "달빛을 받은 꽃 한 송이가 살포시 꽃잎을 열었어요.": "/audio/tts/17qcyg2.mp3",
  "동그란 빨강 풍선이에요. 빨강, 빨강!": "/audio/tts/3e0sod.mp3",
  "동그란 안경": "/audio/tts/ha44bf.mp3",
  "돼": "/audio/tts/4skh.mp3",
  "돼 글자를 찾아요": "/audio/tts/1q25koz.mp3",
  "돼지": "/audio/tts/4fam9.mp3",
  "두구두구": "/audio/tts/1qrl69p.mp3",
  "둥근 달도 환하게 떠올랐어요.": "/audio/tts/1ni2xd0.mp3",
  "둥글고 환한 달도 두둥실 떠올라 온 세상을 비췄어요.": "/audio/tts/1vd1ucy.mp3",
  "딸": "/audio/tts/4st9.mp3",
  "딸 글자를 찾아요": "/audio/tts/1ayuben.mp3",
  "딸기": "/audio/tts/4fd7x.mp3",
  "라벤더 드레스": "/audio/tts/1s3l341.mp3",
  "라벤더 머리": "/audio/tts/1hlo665.mp3",
  "레": "/audio/tts/4td9.mp3",
  "레 글자를 찾아요": "/audio/tts/jrv1u7.mp3",
  "레몬": "/audio/tts/4fy0p.mp3",
  "레몬 드레스": "/audio/tts/10v5noh.mp3",
  "레이스 양산": "/audio/tts/1mrspnq.mp3",
  "로": "/audio/tts/4tfl.mp3",
  "로 글자를 찾아요": "/audio/tts/zjjm8z.mp3",
  "로켓": "/audio/tts/4g46s.mp3",
  "리본 머리띠": "/audio/tts/104us3x.mp3",
  "먼저 앞 단계를 끝내요": "/audio/tts/10qlq8c.mp3",
  "모": "/audio/tts/4tvx.mp3",
  "모 글자를 찾아요": "/audio/tts/3v3h67.mp3",
  "모자": "/audio/tts/4ghod.mp3",
  "무": "/audio/tts/4tzt.mp3",
  "무 글자를 찾아요": "/audio/tts/1htlruj.mp3",
  "무도회장": "/audio/tts/1ruk5gu.mp3",
  "무지개": "/audio/tts/438t85.mp3",
  "물": "/audio/tts/4u01.mp3",
  "물 글자를 찾아요": "/audio/tts/s9j51f.mp3",
  "물고기": "/audio/tts/433s4x.mp3",
  "민트 드레스": "/audio/tts/v99py9.mp3",
  "민트 머리": "/audio/tts/1irby71.mp3",
  "바": "/audio/tts/4u61.mp3",
  "바 글자를 찾아요": "/audio/tts/1ciokyj.mp3",
  "바나나": "/audio/tts/439icp.mp3",
  "바닷가": "/audio/tts/439wwg.mp3",
  "반짝 귀걸이": "/audio/tts/4vs9ae.mp3",
  "반짝이는 노랑 풍선이에요. 노랑, 노랑!": "/audio/tts/7qt4wt.mp3",
  "발": "/audio/tts/4u69.mp3",
  "발 글자를 찾아요": "/audio/tts/myly5f.mp3",
  "밥": "/audio/tts/4u6i.mp3",
  "밥 글자를 찾아요": "/audio/tts/tq30h8.mp3",
  "배": "/audio/tts/4u6t.mp3",
  "배 글자를 찾아요": "/audio/tts/u3jf3r.mp3",
  "배가 불룩해진 친구들은 \"내일 또 만나!\" 하고 손을 흔들며 집으로 돌아갔답니다.": "/audio/tts/oemzr7.mp3",
  "백금발 머리": "/audio/tts/1f6p45a.mp3",
  "버": "/audio/tts/4u95.mp3",
  "버 글자를 찾아요": "/audio/tts/19v7zij.mp3",
  "버스": "/audio/tts/4gstp.mp3",
  "베이지 드레스": "/audio/tts/txx5k1.mp3",
  "별": "/audio/tts/4uax.mp3",
  "별 글자를 찾아요": "/audio/tts/1ihz2yz.mp3",
  "별 왕관": "/audio/tts/1r97rha.mp3",
  "별 지팡이": "/audio/tts/rkn0qm.mp3",
  "별과 달과 꽃이 함께 빛나니, 콩콩이 마음도 반짝반짝 빛났어요.": "/audio/tts/1e27e34.mp3",
  "별밤": "/audio/tts/4gt65.mp3",
  "별이 조금 더 필요해요": "/audio/tts/j03irt.mp3",
  "병아리": "/audio/tts/43hppi.mp3",
  "보": "/audio/tts/4uc9.mp3",
  "보 글자를 찾아요": "/audio/tts/177re2j.mp3",
  "보라": "/audio/tts/4gth1.mp3",
  "보라 드레스": "/audio/tts/1j10tp9.mp3",
  "보라 머리": "/audio/tts/1jh9hy1.mp3",
  "보석 목걸이": "/audio/tts/wd9q6j.mp3",
  "복": "/audio/tts/4uca.mp3",
  "복 글자를 찾아요": "/audio/tts/4i718c.mp3",
  "복숭아": "/audio/tts/43i23v.mp3",
  "복숭아 드레스": "/audio/tts/p3dx03.mp3",
  "분홍 드레스": "/audio/tts/itymv2.mp3",
  "분홍 머리": "/audio/tts/1qzqaca.mp3",
  "분홍 방": "/audio/tts/1sbvm1r.mp3",
  "비": "/audio/tts/4ull.mp3",
  "비 글자를 찾아요": "/audio/tts/z9dlqj.mp3",
  "비행기": "/audio/tts/43t98i.mp3",
  "빨": "/audio/tts/4uml.mp3",
  "빨 글자를 찾아요": "/audio/tts/1qb9v1r.mp3",
  "빨강": "/audio/tts/4h0oy.mp3",
  "빨강 드레스": "/audio/tts/pgcnl6.mp3",
  "빨강 머리": "/audio/tts/1p1grra.mp3",
  "빨강, 파랑, 노랑 풍선이 한데 모이니 무지개처럼 예뻤어요.": "/audio/tts/1hqlt07.mp3",
  "빨강, 파랑, 노랑! 색깔이 모두 모였어요.": "/audio/tts/8iko4o.mp3",
  "빵": "/audio/tts/4umy.mp3",
  "빵 글자를 찾아요": "/audio/tts/1kaplz0.mp3",
  "빵빵! 빨간 자동차가 쌩 지나가요.": "/audio/tts/1m3jjbk.mp3",
  "뽑기 할까요?": "/audio/tts/1pmhg3p.mp3",
  "사": "/audio/tts/4v2p.mp3",
  "사 글자를 찾아요": "/audio/tts/1k6wcs3.mp3",
  "사과": "/audio/tts/4hfn1.mp3",
  "사자": "/audio/tts/4hkw1.mp3",
  "사탕": "/audio/tts/4hmpy.mp3",
  "산": "/audio/tts/4v2t.mp3",
  "산 글자를 찾아요": "/audio/tts/17ev1dj.mp3",
  "샀어요!": "/audio/tts/1srt3xq.mp3",
  "새": "/audio/tts/4v3h.mp3",
  "새 글자를 찾아요": "/audio/tts/11rr6xb.mp3",
  "선글라스": "/audio/tts/1spvr5x.mp3",
  "선물": "/audio/tts/4hlep.mp3",
  "성": "/audio/tts/4v6e.mp3",
  "셋은 사과랑 바나나랑 포도를 사이좋게 나눠 먹었어요. 냠냠!": "/audio/tts/1bx81rl.mp3",
  "손": "/audio/tts/4v91.mp3",
  "손 글자를 찾아요": "/audio/tts/123xuhj.mp3",
  "수": "/audio/tts/4vct.mp3",
  "수 글자를 찾아요": "/audio/tts/ttdelb.mp3",
  "수박": "/audio/tts/4hrw2.mp3",
  "숲속": "/audio/tts/4htms.mp3",
  "스티커 책이에요. 모은 스티커를 눌러 보세요": "/audio/tts/w4vsbg.mp3",
  "시": "/audio/tts/4vi9.mp3",
  "시 글자를 찾아요": "/audio/tts/16xldk3.mp3",
  "시계": "/audio/tts/4htut.mp3",
  "시원한 파랑 풍선이에요. 파랑, 파랑!": "/audio/tts/pg9qh0.mp3",
  "신": "/audio/tts/4vid.mp3",
  "신 글자를 찾아요": "/audio/tts/u5k25j.mp3",
  "신발": "/audio/tts/4hwzl.mp3",
  "아": "/audio/tts/4vzd.mp3",
  "아 글자를 찾아요": "/audio/tts/1rv44ln.mp3",
  "아기": "/audio/tts/4i9tl.mp3",
  "아기 고양이": "/audio/tts/1010o2m.mp3",
  "아기 곰 콩콩이가 살랑살랑 부는 바람을 따라 숲속 길을 걸었어요.": "/audio/tts/q6foku.mp3",
  "아늑한 방": "/audio/tts/qe6igv.mp3",
  "아빠": "/audio/tts/4id0p.mp3",
  "아이보리 드레스": "/audio/tts/e20hdx.mp3",
  "아이스크림": "/audio/tts/tiix0p.mp3",
  "아이템을 모두 모았어요": "/audio/tts/1idnw0t.mp3",
  "아장아장, 막내 아기가 걸음마를 떼며 방긋 웃었어요.": "/audio/tts/8kkdr1.mp3",
  "아장아장, 아기 곰이 걸음마를 해요.": "/audio/tts/7gtwm1.mp3",
  "아쿠아 드레스": "/audio/tts/1qr4vp1.mp3",
  "양": "/audio/tts/4w1i.mp3",
  "양 글자를 찾아요": "/audio/tts/1uhayzc.mp3",
  "양갈래 머리": "/audio/tts/v4grru.mp3",
  "양말": "/audio/tts/4ie2u.mp3",
  "어느 맑은 날, 곰돌이는 친구들과 과일나라로 소풍을 갔어요.": "/audio/tts/1f303ep.mp3",
  "엄": "/audio/tts/4w2x.mp3",
  "엄 글자를 찾아요": "/audio/tts/a3i9jf.mp3",
  "엄마": "/audio/tts/4ifdd.mp3",
  "엄마, 아빠, 아기! 온 가족이 함께라 행복해요.": "/audio/tts/sy3v5r.mp3",
  "엄마와 아빠와 아기까지, 온 가족이 함께라 마음이 따뜻했어요.": "/audio/tts/1huzygr.mp3",
  "없음": "/audio/tts/4ii3b.mp3",
  "에메랄드 드레스": "/audio/tts/3dgd69.mp3",
  "여기는 곰돌이네 집이에요. 가족이 함께 살아요.": "/audio/tts/1apz2gv.mp3",
  "연두 드레스": "/audio/tts/102sp7x.mp3",
  "오늘 배울 단어예요": "/audio/tts/mrb9pd.mp3",
  "올림 머리": "/audio/tts/v2sjgx.mp3",
  "왕관": "/audio/tts/4igje.mp3",
  "왕관 없음": "/audio/tts/ty1tyk.mp3",
  "요술봉": "/audio/tts/453hr6.mp3",
  "요정 날개": "/audio/tts/zardze.mp3",
  "우": "/audio/tts/4w9h.mp3",
  "우 글자를 찾아요": "/audio/tts/11hl6ev.mp3",
  "우유": "/audio/tts/4io0l.mp3",
  "우주": "/audio/tts/4iodt.mp3",
  "원": "/audio/tts/4wad.mp3",
  "원 글자를 찾아요": "/audio/tts/6aep5j.mp3",
  "원숭이": "/audio/tts/454yk6.mp3",
  "유니콘": "/audio/tts/4542zp.mp3",
  "의": "/audio/tts/4we5.mp3",
  "의 글자를 찾아요": "/audio/tts/1x0yb8f.mp3",
  "의자": "/audio/tts/4isdp.mp3",
  "이걸 살까요?": "/audio/tts/b8maf8.mp3",
  "입": "/audio/tts/4wfe.mp3",
  "입 글자를 찾아요": "/audio/tts/vt7kwc.mp3",
  "자": "/audio/tts/4wfp.mp3",
  "자 글자를 찾아요": "/audio/tts/w6nziv.mp3",
  "자동차": "/audio/tts/456vfa.mp3",
  "자동차도 버스도 기차도, 모두 모여 줄지어 달렸어요!": "/audio/tts/iz3d27.mp3",
  "자동차도 버스도 기차도, 모두 모였어요!": "/audio/tts/1gr05hz.mp3",
  "자유롭게 그려 보세요": "/audio/tts/1aheeqy.mp3",
  "자전거": "/audio/tts/45acmh.mp3",
  "자홍 드레스": "/audio/tts/1dshq6i.mp3",
  "잘 듣고 같은 그림을 찾아요": "/audio/tts/16wnxs7.mp3",
  "장": "/audio/tts/4wga.mp3",
  "장 글자를 찾아요": "/audio/tts/m13n0.mp3",
  "장갑": "/audio/tts/4iowr.mp3",
  "장미 드레스": "/audio/tts/27ba5m.mp3",
  "장미 머리": "/audio/tts/12t7v46.mp3",
  "주황 드레스": "/audio/tts/1t32s2.mp3",
  "주황 머리": "/audio/tts/1dk88a6.mp3",
  "진주 티아라": "/audio/tts/1rzfjo5.mp3",
  "집": "/audio/tts/4wvq.mp3",
  "집 글자를 찾아요": "/audio/tts/4rftk.mp3",
  "짠! 새로운 공주님": "/audio/tts/109vtrb.mp3",
  "참 잘했어요!": "/audio/tts/9drgzq.mp3",
  "참 잘했어요! 스티커를 받았어요.": "/audio/tts/3yfaxv.mp3",
  "책": "/audio/tts/4xd6.mp3",
  "책 글자를 찾아요": "/audio/tts/1hraamk.mp3",
  "천사 고리": "/audio/tts/1sgbmhl.mp3",
  "청록 머리": "/audio/tts/1rivtlf.mp3",
  "초": "/audio/tts/4xil.mp3",
  "초 글자를 찾아요": "/audio/tts/yjykgf.mp3",
  "초록": "/audio/tts/4jqga.mp3",
  "칙칙폭폭! 기차가 신나게 달려요.": "/audio/tts/hut7ts.mp3",
  "침": "/audio/tts/4xsd.mp3",
  "침 글자를 찾아요": "/audio/tts/1aijkhb.mp3",
  "침대": "/audio/tts/4jyct.mp3",
  "케": "/audio/tts/4xwl.mp3",
  "케 글자를 찾아요": "/audio/tts/1m4xwxz.mp3",
  "케이크": "/audio/tts/46ivyd.mp3",
  "코": "/audio/tts/4xyx.mp3",
  "코 글자를 찾아요": "/audio/tts/2vifdn.mp3",
  "코끼리": "/audio/tts/46gkbl.mp3",
  "코랄 드레스": "/audio/tts/19ezb9h.mp3",
  "코코아 드레스": "/audio/tts/drjn21.mp3",
  "콩콩이가 길가에 서서 \"무엇이 올까?\" 하고 두근두근 기다렸어요.": "/audio/tts/axd0tj.mp3",
  "콩콩이가 알록달록 풍선을 한 아름 안고 폴짝 나타났어요.": "/audio/tts/x6j5ol.mp3",
  "토": "/audio/tts/4yf9.mp3",
  "토 글자를 찾아요": "/audio/tts/1686c9z.mp3",
  "토끼": "/audio/tts/4kiu9.mp3",
  "토끼 귀": "/audio/tts/1v7qu81.mp3",
  "토끼도 깡충깡충 뛰어왔어요.": "/audio/tts/1yrushz.mp3",
  "트": "/audio/tts/4yn1.mp3",
  "트 글자를 찾아요": "/audio/tts/2ytof.mp3",
  "트럭": "/audio/tts/4krfu.mp3",
  "파": "/audio/tts/4ypd.mp3",
  "파 글자를 찾아요": "/audio/tts/fune37.mp3",
  "파랑": "/audio/tts/4ktia.mp3",
  "펭": "/audio/tts/4ytu.mp3",
  "펭 글자를 찾아요": "/audio/tts/y8isvo.mp3",
  "펭귄": "/audio/tts/4kvo6.mp3",
  "포": "/audio/tts/4yvl.mp3",
  "포 글자를 찾아요": "/audio/tts/ajq777.mp3",
  "포근한 콩콩이네 집, 오늘도 가족이 도란도란 모였어요.": "/audio/tts/zryuzf.mp3",
  "포도": "/audio/tts/4kygl.mp3",
  "풍선": "/audio/tts/4l576.mp3",
  "하": "/audio/tts/4z5p.mp3",
  "하 글자를 찾아요": "/audio/tts/1j7bazj.mp3",
  "하늘 드레스": "/audio/tts/n02l3x.mp3",
  "하늘 머리": "/audio/tts/z4xjbt.mp3",
  "하늘에 반짝반짝 별이 떠올랐어요.": "/audio/tts/19kkp3t.mp3",
  "하양": "/audio/tts/4lb8u.mp3",
  "하트": "/audio/tts/4ldud.mp3",
  "하트 왕관": "/audio/tts/140y8ga.mp3",
  "해": "/audio/tts/4z6h.mp3",
  "해 글자를 찾아요": "/audio/tts/10s654r.mp3",
  "해가 뉘엿뉘엿 질 때, \"오늘 참 즐거웠어!\" 친구들은 손을 흔들었어요.": "/audio/tts/w9c9gq.mp3",
  "해가 지고 깜깜한 밤이 되었어요.": "/audio/tts/fm2zbv.mp3",
  "해님이 산 너머로 쏙 숨고, 까만 밤이 살며시 찾아왔어요.": "/audio/tts/rdo6m2.mp3",
  "햇살이 반짝이던 날, 아기 곰 콩콩이는 친구들과 과일나라로 소풍을 떠났어요.": "/audio/tts/119qje6.mp3",
  "호": "/audio/tts/4zbx.mp3",
  "호 글자를 찾아요": "/audio/tts/1dwe43j.mp3",
  "호랑이": "/audio/tts/47n3gi.mp3",
  "황금 드레스": "/audio/tts/yq467y.mp3",
  "황금 왕관": "/audio/tts/13sr86j.mp3",
  "회색 머리": "/audio/tts/17c4qn2.mp3"
}
